import type { AdminAccount, Booking, Listing, Message, Plan, Settlement, User } from './types'

/**
 * 첫 실행 시 채워지는 예시 데이터.
 * 실제 DB(Prisma) 연결 시 이 파일은 시드 스크립트로 옮기면 된다.
 */

export const SEED_USERS: User[] = [
  {
    id: 'u-admin',
    nickname: '운영자',
    hue: 265,
    phone: '010-0000-0000',
    verified: true,
    role: 'ADMIN',
    region: '서울 강남구',
    intro: '한판 운영팀입니다.',
    photoUrl: null,
    photoStatus: 'NONE',
    createdAt: '2026-07-01T09:00:00.000Z',
    bannedAt: null,
    kept: 0,
    late: 0,
    cancelLate: 0,
    noShow: 0,
    ratingSum: 0,
    reviewCount: 0,
  },
  {
    id: 'u-midking',
    nickname: '미드장인',
    hue: 282,
    phone: '010-1234-5678',
    verified: true,
    role: 'MEMBER',
    region: '서울 강남구',
    intro: '10년째 롤만 합니다. 라인전 위주로 알려드려요.',
    photoUrl: '/mates/midking.jpg',
    photoStatus: 'APPROVED',
    createdAt: '2026-07-03T09:00:00.000Z',
    bannedAt: null,
    kept: 42,
    late: 1,
    cancelLate: 0,
    noShow: 0,
    ratingSum: 210,
    reviewCount: 43,
  },
  {
    id: 'u-newbie',
    nickname: '초보탈출',
    hue: 200,
    phone: '010-2222-3333',
    verified: true,
    role: 'MEMBER',
    region: '서울 마포구',
    intro: '이번에 발로란트 시작했어요. 기초부터 배우고 싶습니다!',
    photoUrl: '/mates/newbie.jpg',
    photoStatus: 'APPROVED',
    createdAt: '2026-07-20T09:00:00.000Z',
    bannedAt: null,
    kept: 3,
    late: 1,
    cancelLate: 1,
    noShow: 0,
    ratingSum: 24,
    reviewCount: 5,
  },
  {
    id: 'u-nightowl',
    nickname: '한밤의궁수',
    hue: 320,
    phone: '010-4444-5555',
    verified: true,
    role: 'MEMBER',
    region: '경기 성남시 분당구',
    intro: '새벽에 같이 게임할 사람 구해요. 즐겜 지향입니다.',
    photoUrl: '/mates/nightowl.jpg',
    photoStatus: 'APPROVED',
    createdAt: '2026-06-11T09:00:00.000Z',
    bannedAt: null,
    kept: 18,
    late: 3,
    cancelLate: 2,
    noShow: 1,
    ratingSum: 96,
    reviewCount: 21,
  },
  {
    id: 'u-coach',
    nickname: '코치정',
    hue: 155,
    phone: '010-6666-7777',
    verified: true,
    role: 'MEMBER',
    region: '부산 부산진구',
    intro: 'FC온라인 전술 코칭. 감독모드 세팅 알려드립니다.',
    photoUrl: '/mates/coach.jpg',
    photoStatus: 'APPROVED',
    createdAt: '2026-05-02T09:00:00.000Z',
    bannedAt: null,
    kept: 67,
    late: 0,
    cancelLate: 1,
    noShow: 0,
    ratingSum: 336,
    reviewCount: 68,
  },
  {
    id: 'u-potato',
    nickname: '감자칩',
    hue: 30,
    phone: '010-8888-9999',
    verified: false,
    role: 'MEMBER',
    region: '서울 관악구',
    intro: '배그 스쿼드 한 자리 비어요. 마이크 필수!',
    photoUrl: '/mates/potato.jpg',
    photoStatus: 'APPROVED',
    createdAt: '2026-08-01T09:00:00.000Z',
    bannedAt: null,
    kept: 0,
    late: 0,
    cancelLate: 0,
    noShow: 0,
    ratingSum: 0,
    reviewCount: 0,
  },
  {
    id: 'u-overtime',
    nickname: '야근전사',
    hue: 95,
    phone: '010-1010-2020',
    verified: true,
    role: 'MEMBER',
    region: '서울 광진구',
    intro: '퇴근하고 오버워치 같이 하실 분. 실력 상관없어요.',
    photoUrl: '/mates/overtime.jpg',
    photoStatus: 'APPROVED',
    createdAt: '2026-07-15T09:00:00.000Z',
    bannedAt: null,
    kept: 11,
    late: 0,
    cancelLate: 0,
    noShow: 0,
    ratingSum: 55,
    reviewCount: 11,
  },
  {
    id: 'u-mapler',
    nickname: '단풍잎',
    hue: 15,
    phone: '010-3030-4040',
    verified: true,
    role: 'MEMBER',
    region: '경기 수원시 영통구',
    intro: '메이플 복귀 유저입니다. 요즘 뭐가 바뀌었는지 알려주실 분?',
    photoUrl: '/mates/mapler.jpg',
    photoStatus: 'APPROVED',
    createdAt: '2026-07-28T09:00:00.000Z',
    bannedAt: null,
    kept: 6,
    late: 0,
    cancelLate: 0,
    noShow: 0,
    ratingSum: 29,
    reviewCount: 6,
  },
]

export const SEED_LISTINGS: Listing[] = [
  {
    id: 'l-1',
    userId: 'u-midking',
    kind: 'TEACH',
    meetMode: 'BOTH',
    title: '롤 라인전 알려드려요 (미드/탑)',
    body: 'CS 놓치는 이유부터 잡아드립니다. 리플레이 같이 보면서 피드백해요. 온라인은 디스코드, 만나서 하실 분은 강남 쪽 PC방에서 가능합니다.',
    mainGame: 'lol',
    games: ['lol'],
    tier: '마스터',
    pricePerHour: 20000,
    region: '서울 강남구',
    pcbang: '레벨업 PC방 강남점',
    availableFrom: '13:00',
    availableTo: '26:00',
    createdAt: '2026-08-04T02:00:00.000Z',
    active: true,
  },
  {
    id: 'l-2',
    userId: 'u-newbie',
    kind: 'LEARN',
    meetMode: 'ONLINE',
    title: '발로란트 진짜 기초부터 알려주세요',
    body: '에임도 없고 맵도 몰라요. 욕 안 하시는 분이면 좋겠습니다. 평일 저녁에 시간 됩니다.',
    mainGame: 'valorant',
    games: ['valorant'],
    tier: '아이언',
    pricePerHour: 10000,
    region: '온라인',
    pcbang: null,
    availableFrom: '19:00',
    availableTo: '23:00',
    createdAt: '2026-08-05T08:30:00.000Z',
    active: true,
  },
  {
    id: 'l-3',
    userId: 'u-nightowl',
    kind: 'PLAY',
    meetMode: 'ONLINE',
    title: '새벽에 롤 같이 하실 분 (즐겜)',
    body: '새벽 1시 이후에 주로 켭니다. 티어 상관없고 그냥 웃으면서 하실 분이면 좋아요. 무료입니다.',
    mainGame: 'lol',
    games: ['lol', 'overwatch'],
    tier: '플래티넘',
    pricePerHour: 0,
    region: '온라인',
    pcbang: null,
    availableFrom: '01:00',
    availableTo: '05:00',
    createdAt: '2026-08-05T15:10:00.000Z',
    active: true,
  },
  {
    id: 'l-4',
    userId: 'u-coach',
    kind: 'TEACH',
    meetMode: 'ONLINE',
    title: 'FC온라인 감독모드·전술 세팅 알려드립니다',
    body: '스쿼드 짜는 법, 전술 수치 조정까지 화면 공유로 알려드려요. 랭크 올리고 싶은 분 환영합니다.',
    mainGame: 'fconline',
    games: ['fconline'],
    tier: '챔피언스',
    pricePerHour: 25000,
    region: '온라인',
    pcbang: null,
    availableFrom: '11:00',
    availableTo: '22:00',
    createdAt: '2026-08-02T05:00:00.000Z',
    active: true,
  },
  {
    id: 'l-5',
    userId: 'u-potato',
    kind: 'PLAY',
    meetMode: 'OFFLINE',
    title: '배그 스쿼드 한 자리 — PC방에서 만나서 해요',
    body: '관악구 근처 PC방에서 주말 오후에 모입니다. 4명 중 1자리 비었어요. 자리값은 각자 부담이고 참가비는 없습니다.',
    mainGame: 'pubg',
    games: ['pubg'],
    tier: '골드',
    pricePerHour: 0,
    region: '서울 관악구',
    pcbang: '레벨업 PC방 신림점',
    availableFrom: '14:00',
    availableTo: '20:00',
    createdAt: '2026-08-06T01:20:00.000Z',
    active: true,
  },
  {
    id: 'l-6',
    userId: 'u-overtime',
    kind: 'PLAY',
    meetMode: 'BOTH',
    title: '퇴근하고 오버워치 한 판씩 같이 해요',
    body: '평일 밤 9시 이후. 경쟁전보다 빠른대전 위주입니다. 광진구 사시면 만나서도 좋고요.',
    mainGame: 'overwatch',
    games: ['overwatch', 'valorant'],
    tier: '다이아',
    pricePerHour: 0,
    region: '서울 광진구',
    pcbang: '레벨업 PC방 건대점',
    availableFrom: '21:00',
    availableTo: '25:00',
    createdAt: '2026-08-05T11:00:00.000Z',
    active: true,
  },
  {
    id: 'l-7',
    userId: 'u-mapler',
    kind: 'LEARN',
    meetMode: 'ONLINE',
    title: '메이플 복귀했는데 뭐부터 해야 할지 알려주세요',
    body: '5년 만에 돌아왔습니다. 육성 루트랑 요즘 사냥터 알려주실 분 찾아요. 사례는 드립니다.',
    mainGame: 'maple',
    games: ['maple'],
    tier: '복귀',
    pricePerHour: 15000,
    region: '온라인',
    pcbang: null,
    availableFrom: '20:00',
    availableTo: '24:00',
    createdAt: '2026-08-03T12:00:00.000Z',
    active: true,
  },
  {
    id: 'l-8',
    userId: 'u-midking',
    kind: 'PLAY',
    meetMode: 'OFFLINE',
    title: '주말에 강남에서 롤 5인큐 하실 분',
    body: '토요일 오후에 PC방에서 5인 모아서 돌립니다. 지금 2자리 남았어요.',
    mainGame: 'lol',
    games: ['lol'],
    tier: '마스터',
    pricePerHour: 0,
    region: '서울 강남구',
    pcbang: '레벨업 PC방 강남점',
    availableFrom: '15:00',
    availableTo: '21:00',
    createdAt: '2026-08-01T07:00:00.000Z',
    active: true,
  },
]

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'b-1',
    listingId: 'l-1',
    memberId: 'u-newbie',
    hostId: 'u-midking',
    startAt: '2026-08-08T11:00:00.000Z',
    hours: 2,
    amount: 40000,
    meetMode: 'ONLINE',
    pcbang: null,
    status: 'CONFIRMED',
    checkInCode: 'LM-4821',
    createdAt: '2026-08-05T09:00:00.000Z',
    settled: false,
  },
  {
    id: 'b-2',
    listingId: 'l-4',
    memberId: 'u-mapler',
    hostId: 'u-coach',
    startAt: '2026-08-04T10:00:00.000Z',
    hours: 1,
    amount: 25000,
    meetMode: 'ONLINE',
    pcbang: null,
    status: 'COMPLETED',
    checkInCode: 'LM-1170',
    createdAt: '2026-08-03T09:00:00.000Z',
    settled: false,
  },
]

export const SEED_MESSAGES: Message[] = [
  {
    id: 'm-1',
    bookingId: 'b-1',
    senderId: 'u-newbie',
    body: '안녕하세요! 토요일 8시에 뵙기로 한 거 맞죠?',
    createdAt: '2026-08-05T09:05:00.000Z',
  },
  {
    id: 'm-2',
    bookingId: 'b-1',
    senderId: 'u-midking',
    body: '네 맞습니다. 디스코드 링크는 시작 10분 전에 여기로 보내드릴게요.',
    createdAt: '2026-08-05T09:12:00.000Z',
  },
]

export const SEED_SETTLEMENTS: Settlement[] = []

export const PC_BANGS = [
  '레벨업 PC방 강남점',
  '레벨업 PC방 신림점',
  '레벨업 PC방 건대점',
  '레벨업 PC방 홍대점',
  '레벨업 PC방 분당서현점',
]

/** 요금제 — 아직 확정 전이라 뼈대만 잡아둔다. 관리자에서 바로 고칠 수 있다. */
export const SEED_PLANS: Plan[] = [
  {
    id: 'p-free',
    name: '무료',
    target: 'MEMBER',
    monthly: 0,
    feeRate: 0.15,
    features: ['글 올리기 무제한', '기본 검색', '앱 내 채팅'],
    active: true,
    note: '',
  },
  {
    id: 'p-mate-basic',
    name: '메이트 베이직',
    target: 'MATE',
    monthly: 0,
    feeRate: 0.15,
    features: ['수수료 15%', '기본 노출'],
    active: true,
    note: '기본 요금제',
  },
  {
    id: 'p-mate-pro',
    name: '메이트 프로',
    target: 'MATE',
    monthly: 9900,
    feeRate: 0.1,
    features: ['수수료 10%', '상단 노출', '프로필 강조', '통계 제공'],
    active: false,
    note: '검토 중',
  },
  {
    id: 'p-pcbang',
    name: '제휴 PC방',
    target: 'PCBANG',
    monthly: 49000,
    feeRate: 0,
    features: ['매장 노출', '체크인 연동', '이벤트 등록'],
    active: false,
    note: '요금 미확정',
  },
]

export const SEED_ADMINS: AdminAccount[] = [
  {
    id: 'a-owner',
    username: 'levelup',
    password: 'levelup',
    name: '최고 관리자',
    owner: true,
    active: true,
    createdAt: '2026-07-01T09:00:00.000Z',
    lastLoginAt: null,
  },
]
